<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/streams/v1/messages.proto

namespace GSols\PHPProto\Queuer\Streams\v1\Metadata;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Stream::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Message::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Stats::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Consumer::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Result::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ç
 queuer/streams/v1/messages.protoqueuer.streams.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.protoqueuer/entities/v1/stream.proto queuer/entities/v1/message.protoqueuer/entities/v1/stats.proto!queuer/entities/v1/consumer.protoqueuer/entities/v1/result.proto"W
CreateStreamRequest
name (	BúBrRname#
owner_id (	BúBr°RownerId"J
CreateStreamResponse2
stream (2.queuer.entities.v1.StreamRstream"9
GetStreamRequest%
	stream_id (	BúBr°RstreamId"G
GetStreamResponse2
stream (2.queuer.entities.v1.StreamRstream";
FlushStreamRequest%
	stream_id (	BúBr°RstreamId"I
FlushStreamResponse2
result (2.queuer.entities.v1.ResultRresult"<
DeleteStreamRequest%
	stream_id (	BúBr°RstreamId"J
DeleteStreamResponse2
result (2.queuer.entities.v1.ResultRresult"u
PublishMessageRequest%
	stream_id (	BúBr°RstreamId5
message (2.queuer.entities.v1.MessageRmessage"A
PublishMessageResponse\'

message_id (	BúBr°R	messageId"9
SubscribeRequest%
	stream_id (	BúBr°RstreamId"J
SubscribeResponse5
message (2.queuer.entities.v1.MessageRmessage"r
UpdateStateRequest%
	stream_id (	BúBr°RstreamId5
state (2.queuer.entities.v1.StreamStateRstate"I
UpdateStateResponse2
result (2.queuer.entities.v1.ResultRresult"k
RegisterConsumerRequest%
	stream_id (	BúBr°RstreamId)
consumer_id (	BúBr°R
consumerId"N
RegisterConsumerResponse2
result (2.queuer.entities.v1.ResultRresult"<
GetConsumersRequest%
	stream_id (	BúBr°RstreamId"R
GetConsumersResponse:
	consumers (2.queuer.entities.v1.ConsumerR	consumers"m
UnregisterConsumerRequest%
	stream_id (	BúBr°RstreamId)
consumer_id (	BúBr°R
consumerId"P
UnregisterConsumerResponse2
result (2.queuer.entities.v1.ResultRresultB~Z-github.com/gsols/goproto/queuer/streams/v1;v1Ê GSols\\PHPProto\\Queuer\\Streams\\v1â)GSols\\PHPProto\\Queuer\\Streams\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

