<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/messages/v1/messages.proto

namespace GSols\PHPProto\Queuer\Messages\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.messages.v1.AcknowledgeRequest</code>
 */
class AcknowledgeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     */
    protected $stream_id = '';
    /**
     * Generated from protobuf field <code>string message_id = 2 [json_name = "messageId", (.validate.rules) = {</code>
     */
    protected $message_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stream_id
     *     @type string $message_id
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Messages\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     * @return string
     */
    public function getStreamId()
    {
        return $this->stream_id;
    }

    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message_id = 2 [json_name = "messageId", (.validate.rules) = {</code>
     * @return string
     */
    public function getMessageId()
    {
        return $this->message_id;
    }

    /**
     * Generated from protobuf field <code>string message_id = 2 [json_name = "messageId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_id = $var;

        return $this;
    }

}

