<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/messages/v1/messages.proto

namespace GSols\PHPProto\Queuer\Messages\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.messages.v1.GetMessagesResponse</code>
 */
class GetMessagesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .queuer.entities.v1.Message messages = 1 [json_name = "messages"];</code>
     */
    private $messages;
    /**
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken", (.validate.rules) = {</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\GSols\PHPProto\Queuer\Entities\v1\Message>|\Google\Protobuf\Internal\RepeatedField $messages
     *     @type string $next_page_token
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Messages\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .queuer.entities.v1.Message messages = 1 [json_name = "messages"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * Generated from protobuf field <code>repeated .queuer.entities.v1.Message messages = 1 [json_name = "messages"];</code>
     * @param array<\GSols\PHPProto\Queuer\Entities\v1\Message>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GSols\PHPProto\Queuer\Entities\v1\Message::class);
        $this->messages = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken", (.validate.rules) = {</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

