<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/messages/v1/messages.proto

namespace GSols\PHPProto\Queuer\Messages\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.messages.v1.GetMessagesRequest</code>
 */
class GetMessagesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     */
    protected $stream_id = '';
    /**
     * Generated from protobuf field <code>string owner_id = 2 [json_name = "ownerId", (.validate.rules) = {</code>
     */
    protected $owner_id = '';
    /**
     * Generated from protobuf field <code>optional string search = 3 [json_name = "search", (.validate.rules) = {</code>
     */
    protected $search = null;
    /**
     * Generated from protobuf field <code>optional string page_token = 4 [json_name = "pageToken"];</code>
     */
    protected $page_token = null;
    /**
     * Generated from protobuf field <code>optional int32 page_size = 5 [json_name = "pageSize", (.validate.rules) = {</code>
     */
    protected $page_size = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stream_id
     *     @type string $owner_id
     *     @type string $search
     *     @type string $page_token
     *     @type int $page_size
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Messages\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     * @return string
     */
    public function getStreamId()
    {
        return $this->stream_id;
    }

    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 2 [json_name = "ownerId", (.validate.rules) = {</code>
     * @return string
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 2 [json_name = "ownerId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string search = 3 [json_name = "search", (.validate.rules) = {</code>
     * @return string
     */
    public function getSearch()
    {
        return isset($this->search) ? $this->search : '';
    }

    public function hasSearch()
    {
        return isset($this->search);
    }

    public function clearSearch()
    {
        unset($this->search);
    }

    /**
     * Generated from protobuf field <code>optional string search = 3 [json_name = "search", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setSearch($var)
    {
        GPBUtil::checkString($var, True);
        $this->search = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string page_token = 4 [json_name = "pageToken"];</code>
     * @return string
     */
    public function getPageToken()
    {
        return isset($this->page_token) ? $this->page_token : '';
    }

    public function hasPageToken()
    {
        return isset($this->page_token);
    }

    public function clearPageToken()
    {
        unset($this->page_token);
    }

    /**
     * Generated from protobuf field <code>optional string page_token = 4 [json_name = "pageToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 page_size = 5 [json_name = "pageSize", (.validate.rules) = {</code>
     * @return int
     */
    public function getPageSize()
    {
        return isset($this->page_size) ? $this->page_size : 0;
    }

    public function hasPageSize()
    {
        return isset($this->page_size);
    }

    public function clearPageSize()
    {
        unset($this->page_size);
    }

    /**
     * Generated from protobuf field <code>optional int32 page_size = 5 [json_name = "pageSize", (.validate.rules) = {</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

}

