<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/streams/v1/messages.proto

namespace GSols\PHPProto\Queuer\Streams\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.streams.v1.PublishMessageRequest</code>
 */
class PublishMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     */
    protected $stream_id = '';
    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Message message = 2 [json_name = "message"];</code>
     */
    protected $message = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stream_id
     *     @type \GSols\PHPProto\Queuer\Entities\v1\Message $message
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Streams\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     * @return string
     */
    public function getStreamId()
    {
        return $this->stream_id;
    }

    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Message message = 2 [json_name = "message"];</code>
     * @return \GSols\PHPProto\Queuer\Entities\v1\Message|null
     */
    public function getMessage()
    {
        return $this->message;
    }

    public function hasMessage()
    {
        return isset($this->message);
    }

    public function clearMessage()
    {
        unset($this->message);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Message message = 2 [json_name = "message"];</code>
     * @param \GSols\PHPProto\Queuer\Entities\v1\Message $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkMessage($var, \GSols\PHPProto\Queuer\Entities\v1\Message::class);
        $this->message = $var;

        return $this;
    }

}

