<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/streams/v1/messages.proto

namespace GSols\PHPProto\Queuer\Streams\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.streams.v1.RegisterRequest</code>
 */
class RegisterRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string id = 1 [json_name = "id", (.validate.rules) = {</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name", (.validate.rules) = {</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string owner_id = 3 [json_name = "ownerId", (.validate.rules) = {</code>
     */
    protected $owner_id = '';
    /**
     * Generated from protobuf field <code>optional string connector = 4 [json_name = "connector", (.validate.rules) = {</code>
     */
    protected $connector = null;
    /**
     * Generated from protobuf field <code>optional int32 port = 5 [json_name = "port", (.validate.rules) = {</code>
     */
    protected $port = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type string $owner_id
     *     @type string $connector
     *     @type int $port
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Streams\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string id = 1 [json_name = "id", (.validate.rules) = {</code>
     * @return string
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : '';
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional string id = 1 [json_name = "id", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name", (.validate.rules) = {</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 3 [json_name = "ownerId", (.validate.rules) = {</code>
     * @return string
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 3 [json_name = "ownerId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string connector = 4 [json_name = "connector", (.validate.rules) = {</code>
     * @return string
     */
    public function getConnector()
    {
        return isset($this->connector) ? $this->connector : '';
    }

    public function hasConnector()
    {
        return isset($this->connector);
    }

    public function clearConnector()
    {
        unset($this->connector);
    }

    /**
     * Generated from protobuf field <code>optional string connector = 4 [json_name = "connector", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setConnector($var)
    {
        GPBUtil::checkString($var, True);
        $this->connector = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 port = 5 [json_name = "port", (.validate.rules) = {</code>
     * @return int
     */
    public function getPort()
    {
        return isset($this->port) ? $this->port : 0;
    }

    public function hasPort()
    {
        return isset($this->port);
    }

    public function clearPort()
    {
        unset($this->port);
    }

    /**
     * Generated from protobuf field <code>optional int32 port = 5 [json_name = "port", (.validate.rules) = {</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->port = $var;

        return $this;
    }

}

