<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/streams/v1/messages.proto

namespace GSols\PHPProto\Queuer\Streams\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.streams.v1.UpdateStateRequest</code>
 */
class UpdateStateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     */
    protected $stream_id = '';
    /**
     * Generated from protobuf field <code>.queuer.entities.v1.StreamState state = 2 [json_name = "state"];</code>
     */
    protected $state = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stream_id
     *     @type int $state
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Streams\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     * @return string
     */
    public function getStreamId()
    {
        return $this->stream_id;
    }

    /**
     * Generated from protobuf field <code>string stream_id = 1 [json_name = "streamId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.StreamState state = 2 [json_name = "state"];</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.StreamState state = 2 [json_name = "state"];</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \GSols\PHPProto\Queuer\Entities\v1\StreamState::class);
        $this->state = $var;

        return $this;
    }

}

