<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/owners/v1/messages.proto

namespace GSols\PHPProto\Queuer\Owners\v1\Metadata;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Owner::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Stream::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Consumer::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Result::initOnce();
        $pool->internalAddGeneratedFile(
            '
è	
queuer/owners/v1/messages.protoqueuer.owners.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.protoqueuer/entities/v1/owner.protoqueuer/entities/v1/stream.proto!queuer/entities/v1/consumer.protoqueuer/entities/v1/result.proto"1
CreateOwnerRequest
name (	B˙BrRname"F
CreateOwnerResponse/
owner (2.queuer.entities.v1.OwnerRowner"6
GetOwnerRequest#
owner_id (	B˙Br∞RownerId"C
GetOwnerResponse/
owner (2.queuer.entities.v1.OwnerRowner"9
ListStreamsRequest#
owner_id (	B˙Br∞RownerId"K
ListStreamsResponse4
streams (2.queuer.entities.v1.StreamRstreams"i
RegisterConsumerRequest#
owner_id (	B˙Br∞RownerId)
consumer_id (	B˙Br∞R
consumerId"=
RegisterConsumerResponse!
issued_token (	RissuedToken":
GetConsumersRequest#
owner_id (	B˙Br∞RownerId"R
GetConsumersResponse:
	consumers (2.queuer.entities.v1.ConsumerR	consumersB{Z,github.com/gsols/goproto/queuer/owners/v1;v1 GSols\\PHPProto\\Queuer\\Owners\\v1‚(GSols\\PHPProto\\Queuer\\Owners\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

