<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/owners/v1/owner.proto

namespace GSols\PHPProto\Queuer\Owners\v1\Metadata;

class Owner
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Owner::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Stream::initOnce();
        \GSols\PHPProto\Queuer\Owners\v1\Metadata\Messages::initOnce();
        $pool->internalAddGeneratedFile(
            '
 
queuer/owners/v1/owner.protoqueuer.owners.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.protoqueuer/entities/v1/owner.protoqueuer/entities/v1/stream.protoqueuer/owners/v1/messages.proto2ò
OwnerServiceq
CreateOwner$.queuer.owners.v1.CreateOwnerRequest%.queuer.owners.v1.CreateOwnerResponse"Ç”‰ì:*"
/v1/ownersp
GetOwner!.queuer.owners.v1.GetOwnerRequest".queuer.owners.v1.GetOwnerResponse"Ç”‰ì/v1/owners/{owner_id}ï
RegisterConsumer).queuer.owners.v1.RegisterConsumerRequest*.queuer.owners.v1.RegisterConsumerResponse"*Ç”‰ì$:*"/v1/owners/{owner_id}/consumersÜ
GetConsumers%.queuer.owners.v1.GetConsumersRequest&.queuer.owners.v1.GetConsumersResponse"\'Ç”‰ì!/v1/owners/{owner_id}/consumersÅ
ListStreams$.queuer.owners.v1.ListStreamsRequest%.queuer.owners.v1.ListStreamsResponse"%Ç”‰ì/v1/owners/{owner_id}/streamsB{Z,github.com/gsols/goproto/queuer/owners/v1;v1 GSols\\PHPProto\\Queuer\\Owners\\v1‚(GSols\\PHPProto\\Queuer\\Owners\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

