<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/consumers/v1/messages.proto

namespace GSols\PHPProto\Queuer\Consumers\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.consumers.v1.GetConsumerResponse</code>
 */
class GetConsumerResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Consumer consumer = 1 [json_name = "consumer"];</code>
     */
    protected $consumer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GSols\PHPProto\Queuer\Entities\v1\Consumer $consumer
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Consumers\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Consumer consumer = 1 [json_name = "consumer"];</code>
     * @return \GSols\PHPProto\Queuer\Entities\v1\Consumer|null
     */
    public function getConsumer()
    {
        return $this->consumer;
    }

    public function hasConsumer()
    {
        return isset($this->consumer);
    }

    public function clearConsumer()
    {
        unset($this->consumer);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Consumer consumer = 1 [json_name = "consumer"];</code>
     * @param \GSols\PHPProto\Queuer\Entities\v1\Consumer $var
     * @return $this
     */
    public function setConsumer($var)
    {
        GPBUtil::checkMessage($var, \GSols\PHPProto\Queuer\Entities\v1\Consumer::class);
        $this->consumer = $var;

        return $this;
    }

}

