<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/consumers/v1/messages.proto

namespace GSols\PHPProto\Queuer\Consumers\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.consumers.v1.RegisterConsumerRequest</code>
 */
class RegisterConsumerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Consumer consumer = 1 [json_name = "consumer", (.validate.rules) = {</code>
     */
    protected $consumer = null;
    /**
     * Generated from protobuf field <code>bytes public_key = 2 [json_name = "publicKey", (.validate.rules) = {</code>
     */
    protected $public_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GSols\PHPProto\Queuer\Entities\v1\Consumer $consumer
     *     @type string $public_key
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Consumers\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Consumer consumer = 1 [json_name = "consumer", (.validate.rules) = {</code>
     * @return \GSols\PHPProto\Queuer\Entities\v1\Consumer|null
     */
    public function getConsumer()
    {
        return $this->consumer;
    }

    public function hasConsumer()
    {
        return isset($this->consumer);
    }

    public function clearConsumer()
    {
        unset($this->consumer);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Consumer consumer = 1 [json_name = "consumer", (.validate.rules) = {</code>
     * @param \GSols\PHPProto\Queuer\Entities\v1\Consumer $var
     * @return $this
     */
    public function setConsumer($var)
    {
        GPBUtil::checkMessage($var, \GSols\PHPProto\Queuer\Entities\v1\Consumer::class);
        $this->consumer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes public_key = 2 [json_name = "publicKey", (.validate.rules) = {</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>bytes public_key = 2 [json_name = "publicKey", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->public_key = $var;

        return $this;
    }

}

