<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/command.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use UnexpectedValueException;

/**
 * Protobuf type <code>queuer.entities.v1.CommandStatus</code>
 */
class CommandStatus
{
    /**
     * Generated from protobuf enum <code>COMMAND_STATUS_UNSPECIFIED = 0;</code>
     */
    const COMMAND_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>COMMAND_STATUS_PENDING = 1;</code>
     */
    const COMMAND_STATUS_PENDING = 1;
    /**
     * Generated from protobuf enum <code>COMMAND_STATUS_IN_PROGRESS = 2;</code>
     */
    const COMMAND_STATUS_IN_PROGRESS = 2;
    /**
     * Generated from protobuf enum <code>COMMAND_STATUS_COMPLETED = 3;</code>
     */
    const COMMAND_STATUS_COMPLETED = 3;
    /**
     * Generated from protobuf enum <code>COMMAND_STATUS_FAILED = 4;</code>
     */
    const COMMAND_STATUS_FAILED = 4;

    private static $valueToName = [
        self::COMMAND_STATUS_UNSPECIFIED => 'COMMAND_STATUS_UNSPECIFIED',
        self::COMMAND_STATUS_PENDING => 'COMMAND_STATUS_PENDING',
        self::COMMAND_STATUS_IN_PROGRESS => 'COMMAND_STATUS_IN_PROGRESS',
        self::COMMAND_STATUS_COMPLETED => 'COMMAND_STATUS_COMPLETED',
        self::COMMAND_STATUS_FAILED => 'COMMAND_STATUS_FAILED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

