<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/command.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use UnexpectedValueException;

/**
 * Protobuf type <code>queuer.entities.v1.CommandAction</code>
 */
class CommandAction
{
    /**
     * Generated from protobuf enum <code>COMMAND_ACTION_UNSPECIFIED = 0;</code>
     */
    const COMMAND_ACTION_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>COMMAND_ACTION_REQ_RESTART_SERVICE = 1;</code>
     */
    const COMMAND_ACTION_REQ_RESTART_SERVICE = 1;
    /**
     * Generated from protobuf enum <code>COMMAND_ACTION_REQ_REBOOT_SYSTEM = 2;</code>
     */
    const COMMAND_ACTION_REQ_REBOOT_SYSTEM = 2;
    /**
     * Generated from protobuf enum <code>COMMAND_ACTION_REQ_NETWORK_SPEED = 3;</code>
     */
    const COMMAND_ACTION_REQ_NETWORK_SPEED = 3;
    /**
     * Generated from protobuf enum <code>COMMAND_ACTION_REQ_UPDATE_SERVICE = 4;</code>
     */
    const COMMAND_ACTION_REQ_UPDATE_SERVICE = 4;

    private static $valueToName = [
        self::COMMAND_ACTION_UNSPECIFIED => 'COMMAND_ACTION_UNSPECIFIED',
        self::COMMAND_ACTION_REQ_RESTART_SERVICE => 'COMMAND_ACTION_REQ_RESTART_SERVICE',
        self::COMMAND_ACTION_REQ_REBOOT_SYSTEM => 'COMMAND_ACTION_REQ_REBOOT_SYSTEM',
        self::COMMAND_ACTION_REQ_NETWORK_SPEED => 'COMMAND_ACTION_REQ_NETWORK_SPEED',
        self::COMMAND_ACTION_REQ_UPDATE_SERVICE => 'COMMAND_ACTION_REQ_UPDATE_SERVICE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

