<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/consumer.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.entities.v1.ConsumerInfo</code>
 */
class ConsumerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.queuer.entities.v1.HostInfo host = 1 [json_name = "host"];</code>
     */
    protected $host = null;
    /**
     * Generated from protobuf field <code>.queuer.entities.v1.ProcessInfo process = 2 [json_name = "process"];</code>
     */
    protected $process = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GSols\PHPProto\Queuer\Entities\v1\HostInfo $host
     *     @type \GSols\PHPProto\Queuer\Entities\v1\ProcessInfo $process
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Consumer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.HostInfo host = 1 [json_name = "host"];</code>
     * @return \GSols\PHPProto\Queuer\Entities\v1\HostInfo|null
     */
    public function getHost()
    {
        return $this->host;
    }

    public function hasHost()
    {
        return isset($this->host);
    }

    public function clearHost()
    {
        unset($this->host);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.HostInfo host = 1 [json_name = "host"];</code>
     * @param \GSols\PHPProto\Queuer\Entities\v1\HostInfo $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkMessage($var, \GSols\PHPProto\Queuer\Entities\v1\HostInfo::class);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.ProcessInfo process = 2 [json_name = "process"];</code>
     * @return \GSols\PHPProto\Queuer\Entities\v1\ProcessInfo|null
     */
    public function getProcess()
    {
        return $this->process;
    }

    public function hasProcess()
    {
        return isset($this->process);
    }

    public function clearProcess()
    {
        unset($this->process);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.ProcessInfo process = 2 [json_name = "process"];</code>
     * @param \GSols\PHPProto\Queuer\Entities\v1\ProcessInfo $var
     * @return $this
     */
    public function setProcess($var)
    {
        GPBUtil::checkMessage($var, \GSols\PHPProto\Queuer\Entities\v1\ProcessInfo::class);
        $this->process = $var;

        return $this;
    }

}

