<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/stats.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.entities.v1.CPUStats</code>
 */
class CPUStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 user = 1 [json_name = "user"];</code>
     */
    protected $user = 0;
    /**
     * Generated from protobuf field <code>uint64 system = 2 [json_name = "system"];</code>
     */
    protected $system = 0;
    /**
     * Generated from protobuf field <code>uint64 idle = 3 [json_name = "idle"];</code>
     */
    protected $idle = 0;
    /**
     * Generated from protobuf field <code>uint64 total = 4 [json_name = "total"];</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user
     *     @type int|string $system
     *     @type int|string $idle
     *     @type int|string $total
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Stats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 user = 1 [json_name = "user"];</code>
     * @return int|string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>uint64 user = 1 [json_name = "user"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkUint64($var);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 system = 2 [json_name = "system"];</code>
     * @return int|string
     */
    public function getSystem()
    {
        return $this->system;
    }

    /**
     * Generated from protobuf field <code>uint64 system = 2 [json_name = "system"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setSystem($var)
    {
        GPBUtil::checkUint64($var);
        $this->system = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 idle = 3 [json_name = "idle"];</code>
     * @return int|string
     */
    public function getIdle()
    {
        return $this->idle;
    }

    /**
     * Generated from protobuf field <code>uint64 idle = 3 [json_name = "idle"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setIdle($var)
    {
        GPBUtil::checkUint64($var);
        $this->idle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 total = 4 [json_name = "total"];</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>uint64 total = 4 [json_name = "total"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint64($var);
        $this->total = $var;

        return $this;
    }

}

