<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/consumer.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.entities.v1.HostInfo</code>
 */
class HostInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string os = 1 [json_name = "os", (.validate.rules) = {</code>
     */
    protected $os = '';
    /**
     * Generated from protobuf field <code>string arch = 2 [json_name = "arch", (.validate.rules) = {</code>
     */
    protected $arch = '';
    /**
     * Generated from protobuf field <code>string ip = 3 [json_name = "ip", (.validate.rules) = {</code>
     */
    protected $ip = '';
    /**
     * Generated from protobuf field <code>string hostname = 4 [json_name = "hostname", (.validate.rules) = {</code>
     */
    protected $hostname = '';
    /**
     * Generated from protobuf field <code>string boot_time = 5 [json_name = "bootTime", (.validate.rules) = {</code>
     */
    protected $boot_time = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $os
     *     @type string $arch
     *     @type string $ip
     *     @type string $hostname
     *     @type string $boot_time
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Consumer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string os = 1 [json_name = "os", (.validate.rules) = {</code>
     * @return string
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     * Generated from protobuf field <code>string os = 1 [json_name = "os", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOs($var)
    {
        GPBUtil::checkString($var, True);
        $this->os = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string arch = 2 [json_name = "arch", (.validate.rules) = {</code>
     * @return string
     */
    public function getArch()
    {
        return $this->arch;
    }

    /**
     * Generated from protobuf field <code>string arch = 2 [json_name = "arch", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setArch($var)
    {
        GPBUtil::checkString($var, True);
        $this->arch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip = 3 [json_name = "ip", (.validate.rules) = {</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 3 [json_name = "ip", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hostname = 4 [json_name = "hostname", (.validate.rules) = {</code>
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * Generated from protobuf field <code>string hostname = 4 [json_name = "hostname", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string boot_time = 5 [json_name = "bootTime", (.validate.rules) = {</code>
     * @return string
     */
    public function getBootTime()
    {
        return $this->boot_time;
    }

    /**
     * Generated from protobuf field <code>string boot_time = 5 [json_name = "bootTime", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setBootTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->boot_time = $var;

        return $this;
    }

}

