<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/stats.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.entities.v1.LoadStats</code>
 */
class LoadStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float one = 1 [json_name = "one"];</code>
     */
    protected $one = 0.0;
    /**
     * Generated from protobuf field <code>float five = 2 [json_name = "five"];</code>
     */
    protected $five = 0.0;
    /**
     * Generated from protobuf field <code>float fifteen = 3 [json_name = "fifteen"];</code>
     */
    protected $fifteen = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $one
     *     @type float $five
     *     @type float $fifteen
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Stats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float one = 1 [json_name = "one"];</code>
     * @return float
     */
    public function getOne()
    {
        return $this->one;
    }

    /**
     * Generated from protobuf field <code>float one = 1 [json_name = "one"];</code>
     * @param float $var
     * @return $this
     */
    public function setOne($var)
    {
        GPBUtil::checkFloat($var);
        $this->one = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float five = 2 [json_name = "five"];</code>
     * @return float
     */
    public function getFive()
    {
        return $this->five;
    }

    /**
     * Generated from protobuf field <code>float five = 2 [json_name = "five"];</code>
     * @param float $var
     * @return $this
     */
    public function setFive($var)
    {
        GPBUtil::checkFloat($var);
        $this->five = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float fifteen = 3 [json_name = "fifteen"];</code>
     * @return float
     */
    public function getFifteen()
    {
        return $this->fifteen;
    }

    /**
     * Generated from protobuf field <code>float fifteen = 3 [json_name = "fifteen"];</code>
     * @param float $var
     * @return $this
     */
    public function setFifteen($var)
    {
        GPBUtil::checkFloat($var);
        $this->fifteen = $var;

        return $this;
    }

}

