<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/stats.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.entities.v1.NetworkSpeed</code>
 */
class NetworkSpeed extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float download = 1 [json_name = "download"];</code>
     */
    protected $download = 0.0;
    /**
     * Generated from protobuf field <code>float upload = 2 [json_name = "upload"];</code>
     */
    protected $upload = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $download
     *     @type float $upload
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Stats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float download = 1 [json_name = "download"];</code>
     * @return float
     */
    public function getDownload()
    {
        return $this->download;
    }

    /**
     * Generated from protobuf field <code>float download = 1 [json_name = "download"];</code>
     * @param float $var
     * @return $this
     */
    public function setDownload($var)
    {
        GPBUtil::checkFloat($var);
        $this->download = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float upload = 2 [json_name = "upload"];</code>
     * @return float
     */
    public function getUpload()
    {
        return $this->upload;
    }

    /**
     * Generated from protobuf field <code>float upload = 2 [json_name = "upload"];</code>
     * @param float $var
     * @return $this
     */
    public function setUpload($var)
    {
        GPBUtil::checkFloat($var);
        $this->upload = $var;

        return $this;
    }

}

