<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/owner.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.entities.v1.Owner</code>
 */
class Owner extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.validate.rules) = {</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name", (.validate.rules) = {</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>optional int32 consumers = 3 [json_name = "consumers"];</code>
     */
    protected $consumers = null;
    /**
     * Generated from protobuf field <code>optional int32 streams = 4 [json_name = "streams"];</code>
     */
    protected $streams = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type int $consumers
     *     @type int $streams
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Owner::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.validate.rules) = {</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name", (.validate.rules) = {</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 consumers = 3 [json_name = "consumers"];</code>
     * @return int
     */
    public function getConsumers()
    {
        return isset($this->consumers) ? $this->consumers : 0;
    }

    public function hasConsumers()
    {
        return isset($this->consumers);
    }

    public function clearConsumers()
    {
        unset($this->consumers);
    }

    /**
     * Generated from protobuf field <code>optional int32 consumers = 3 [json_name = "consumers"];</code>
     * @param int $var
     * @return $this
     */
    public function setConsumers($var)
    {
        GPBUtil::checkInt32($var);
        $this->consumers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 streams = 4 [json_name = "streams"];</code>
     * @return int
     */
    public function getStreams()
    {
        return isset($this->streams) ? $this->streams : 0;
    }

    public function hasStreams()
    {
        return isset($this->streams);
    }

    public function clearStreams()
    {
        unset($this->streams);
    }

    /**
     * Generated from protobuf field <code>optional int32 streams = 4 [json_name = "streams"];</code>
     * @param int $var
     * @return $this
     */
    public function setStreams($var)
    {
        GPBUtil::checkInt32($var);
        $this->streams = $var;

        return $this;
    }

}

