<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/message.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use UnexpectedValueException;

/**
 * Protobuf type <code>queuer.entities.v1.Priority</code>
 */
class Priority
{
    /**
     * Generated from protobuf enum <code>PRIORITY_UNSPECIFIED = 0;</code>
     */
    const PRIORITY_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>PRIORITY_LOW = 1;</code>
     */
    const PRIORITY_LOW = 1;
    /**
     * Generated from protobuf enum <code>PRIORITY_NORMAL = 2;</code>
     */
    const PRIORITY_NORMAL = 2;
    /**
     * Generated from protobuf enum <code>PRIORITY_HIGH = 3;</code>
     */
    const PRIORITY_HIGH = 3;

    private static $valueToName = [
        self::PRIORITY_UNSPECIFIED => 'PRIORITY_UNSPECIFIED',
        self::PRIORITY_LOW => 'PRIORITY_LOW',
        self::PRIORITY_NORMAL => 'PRIORITY_NORMAL',
        self::PRIORITY_HIGH => 'PRIORITY_HIGH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

