<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/stats.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.entities.v1.Stats</code>
 */
class Stats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.queuer.entities.v1.CPUStats cpu = 1 [json_name = "cpu"];</code>
     */
    protected $cpu = null;
    /**
     * Generated from protobuf field <code>.queuer.entities.v1.LoadStats load = 2 [json_name = "load"];</code>
     */
    protected $load = null;
    /**
     * Generated from protobuf field <code>.queuer.entities.v1.MemoryStats memory = 3 [json_name = "memory"];</code>
     */
    protected $memory = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GSols\PHPProto\Queuer\Entities\v1\CPUStats $cpu
     *     @type \GSols\PHPProto\Queuer\Entities\v1\LoadStats $load
     *     @type \GSols\PHPProto\Queuer\Entities\v1\MemoryStats $memory
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Stats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.CPUStats cpu = 1 [json_name = "cpu"];</code>
     * @return \GSols\PHPProto\Queuer\Entities\v1\CPUStats|null
     */
    public function getCpu()
    {
        return $this->cpu;
    }

    public function hasCpu()
    {
        return isset($this->cpu);
    }

    public function clearCpu()
    {
        unset($this->cpu);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.CPUStats cpu = 1 [json_name = "cpu"];</code>
     * @param \GSols\PHPProto\Queuer\Entities\v1\CPUStats $var
     * @return $this
     */
    public function setCpu($var)
    {
        GPBUtil::checkMessage($var, \GSols\PHPProto\Queuer\Entities\v1\CPUStats::class);
        $this->cpu = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.LoadStats load = 2 [json_name = "load"];</code>
     * @return \GSols\PHPProto\Queuer\Entities\v1\LoadStats|null
     */
    public function getLoad()
    {
        return $this->load;
    }

    public function hasLoad()
    {
        return isset($this->load);
    }

    public function clearLoad()
    {
        unset($this->load);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.LoadStats load = 2 [json_name = "load"];</code>
     * @param \GSols\PHPProto\Queuer\Entities\v1\LoadStats $var
     * @return $this
     */
    public function setLoad($var)
    {
        GPBUtil::checkMessage($var, \GSols\PHPProto\Queuer\Entities\v1\LoadStats::class);
        $this->load = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.MemoryStats memory = 3 [json_name = "memory"];</code>
     * @return \GSols\PHPProto\Queuer\Entities\v1\MemoryStats|null
     */
    public function getMemory()
    {
        return $this->memory;
    }

    public function hasMemory()
    {
        return isset($this->memory);
    }

    public function clearMemory()
    {
        unset($this->memory);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.MemoryStats memory = 3 [json_name = "memory"];</code>
     * @param \GSols\PHPProto\Queuer\Entities\v1\MemoryStats $var
     * @return $this
     */
    public function setMemory($var)
    {
        GPBUtil::checkMessage($var, \GSols\PHPProto\Queuer\Entities\v1\MemoryStats::class);
        $this->memory = $var;

        return $this;
    }

}

