<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/stream.proto

namespace GSols\PHPProto\Queuer\Entities\v1;

use UnexpectedValueException;

/**
 * Protobuf type <code>queuer.entities.v1.StreamState</code>
 */
class StreamState
{
    /**
     * Generated from protobuf enum <code>STREAM_STATE_UNSPECIFIED = 0;</code>
     */
    const STREAM_STATE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>STREAM_STATE_ACTIVE = 1;</code>
     */
    const STREAM_STATE_ACTIVE = 1;
    /**
     * Generated from protobuf enum <code>STREAM_STATE_INACTIVE = 2;</code>
     */
    const STREAM_STATE_INACTIVE = 2;
    /**
     * Generated from protobuf enum <code>STREAM_STATE_PAUSED = 3;</code>
     */
    const STREAM_STATE_PAUSED = 3;

    private static $valueToName = [
        self::STREAM_STATE_UNSPECIFIED => 'STREAM_STATE_UNSPECIFIED',
        self::STREAM_STATE_ACTIVE => 'STREAM_STATE_ACTIVE',
        self::STREAM_STATE_INACTIVE => 'STREAM_STATE_INACTIVE',
        self::STREAM_STATE_PAUSED => 'STREAM_STATE_PAUSED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

