<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/owners/v1/messages.proto

namespace GSols\PHPProto\Queuer\Owners\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.owners.v1.GetOwnersResponse</code>
 */
class GetOwnersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .queuer.entities.v1.Owner owners = 1 [json_name = "owners"];</code>
     */
    private $owners;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\GSols\PHPProto\Queuer\Entities\v1\Owner>|\Google\Protobuf\Internal\RepeatedField $owners
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Owners\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .queuer.entities.v1.Owner owners = 1 [json_name = "owners"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOwners()
    {
        return $this->owners;
    }

    /**
     * Generated from protobuf field <code>repeated .queuer.entities.v1.Owner owners = 1 [json_name = "owners"];</code>
     * @param array<\GSols\PHPProto\Queuer\Entities\v1\Owner>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOwners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GSols\PHPProto\Queuer\Entities\v1\Owner::class);
        $this->owners = $arr;

        return $this;
    }

}

