<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/owners/v1/messages.proto

namespace GSols\PHPProto\Queuer\Owners\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.owners.v1.RegisterConsumerRequest</code>
 */
class RegisterConsumerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string owner_id = 1 [json_name = "ownerId", (.validate.rules) = {</code>
     */
    protected $owner_id = '';
    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Consumer consumer = 2 [json_name = "consumer"];</code>
     */
    protected $consumer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $owner_id
     *     @type \GSols\PHPProto\Queuer\Entities\v1\Consumer $consumer
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Owners\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string owner_id = 1 [json_name = "ownerId", (.validate.rules) = {</code>
     * @return string
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 1 [json_name = "ownerId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Consumer consumer = 2 [json_name = "consumer"];</code>
     * @return \GSols\PHPProto\Queuer\Entities\v1\Consumer|null
     */
    public function getConsumer()
    {
        return $this->consumer;
    }

    public function hasConsumer()
    {
        return isset($this->consumer);
    }

    public function clearConsumer()
    {
        unset($this->consumer);
    }

    /**
     * Generated from protobuf field <code>.queuer.entities.v1.Consumer consumer = 2 [json_name = "consumer"];</code>
     * @param \GSols\PHPProto\Queuer\Entities\v1\Consumer $var
     * @return $this
     */
    public function setConsumer($var)
    {
        GPBUtil::checkMessage($var, \GSols\PHPProto\Queuer\Entities\v1\Consumer::class);
        $this->consumer = $var;

        return $this;
    }

}

