<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/owners/v1/messages.proto

namespace GSols\PHPProto\Queuer\Owners\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>queuer.owners.v1.RegisterConsumerResponse</code>
 */
class RegisterConsumerResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string issued_token = 1 [json_name = "issuedToken"];</code>
     */
    protected $issued_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $issued_token
     * }
     */
    public function __construct($data = NULL) {
        \GSols\PHPProto\Queuer\Owners\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string issued_token = 1 [json_name = "issuedToken"];</code>
     * @return string
     */
    public function getIssuedToken()
    {
        return $this->issued_token;
    }

    /**
     * Generated from protobuf field <code>string issued_token = 1 [json_name = "issuedToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setIssuedToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->issued_token = $var;

        return $this;
    }

}

