<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/consumer.proto

namespace GSols\PHPProto\Queuer\Entities\v1\Metadata;

class Consumer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Owner::initOnce();
        $pool->internalAddGeneratedFile(
            '
û
!queuer/entities/v1/consumer.protoqueuer.entities.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.protoqueuer/entities/v1/owner.proto"‘
Consumer
id (	BúBr°Rid0
host (2.queuer.entities.v1.HostInfoRhost9
process (2.queuer.entities.v1.ProcessInfoRprocess"¤
HostInfo
os (	BúBrRos
arch (	BúBrRarch
ip (	BúBrRip#
hostname (	BúBrRhostname$
	boot_time (	BúBrRbootTime"C
ProcessInfo
pid (	BúBrRpid
uid (	BúBrRuidBZ.github.com/gsols/goproto/queuer/entities/v1;v1Ê!GSols\\PHPProto\\Queuer\\Entities\\v1â*GSols\\PHPProto\\Queuer\\Entities\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

