<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/entities/v1/stats.proto

namespace GSols\PHPProto\Queuer\Entities\v1\Metadata;

class Stats
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        $pool->internalAddGeneratedFile(
            '
‹
queuer/entities/v1/stats.protoqueuer.entities.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.proto"`
CPUStats
user (Ruser
system (Rsystem
idle (Ridle
total (Rtotal"i
MemoryStats
total (Rtotal
used (Rused
	available (R	available
free (Rfree"K
	LoadStats
one (Rone
five (Rfive
fifteen (Rfifteen"B
NetworkSpeed
download (Rdownload
upload (Rupload"£
Stats.
cpu (2.queuer.entities.v1.CPUStatsRcpu1
load (2.queuer.entities.v1.LoadStatsRload7
memory (2.queuer.entities.v1.MemoryStatsRmemoryBÅZ.github.com/gsols/goproto/queuer/entities/v1;v1 !GSols\\PHPProto\\Queuer\\Entities\\v1‚*GSols\\PHPProto\\Queuer\\Entities\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

