<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/messages/v1/messages.proto

namespace GSols\PHPProto\Queuer\Messages\v1\Metadata;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Message::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Result::initOnce();
        $pool->internalAddGeneratedFile(
            '
œ
!queuer/messages/v1/messages.protoqueuer.messages.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.proto queuer/entities/v1/message.protoqueuer/entities/v1/result.proto"d
AcknowledgeRequest%
	stream_id (	B˙Br∞RstreamId\'

message_id (	B˙Br∞R	messageId"I
AcknowledgeResponse2
result (2.queuer.entities.v1.ResultRresultBÅZ.github.com/gsols/goproto/queuer/messages/v1;v1 !GSols\\PHPProto\\Queuer\\Messages\\v1‚*GSols\\PHPProto\\Queuer\\Messages\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

