<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/messages/v1/service.proto

namespace GSols\PHPProto\Queuer\Messages\v1\Metadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Message::initOnce();
        \GSols\PHPProto\Queuer\Messages\v1\Metadata\Messages::initOnce();
        $pool->internalAddGeneratedFile(
            '
¡
 queuer/messages/v1/service.protoqueuer.messages.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.proto queuer/entities/v1/message.proto!queuer/messages/v1/messages.proto2ü
MessageServiceå
Acknowledge&.queuer.messages.v1.AcknowledgeRequest\'.queuer.messages.v1.AcknowledgeResponse",Ç”‰ì&:*"!/v1/messages/{message_id}/confirmBÅZ.github.com/gsols/goproto/queuer/messages/v1;v1 !GSols\\PHPProto\\Queuer\\Messages\\v1‚*GSols\\PHPProto\\Queuer\\Messages\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

