<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queuer/consumers/v1/messages.proto

namespace GSols\PHPProto\Queuer\Consumers\v1\Metadata;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Consumer::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Stream::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Message::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Command::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Stats::initOnce();
        \GSols\PHPProto\Queuer\Entities\v1\Metadata\Result::initOnce();
        $pool->internalAddGeneratedFile(
            '
˜
"queuer/consumers/v1/messages.protoqueuer.consumers.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.proto!queuer/entities/v1/consumer.protoqueuer/entities/v1/stream.proto queuer/entities/v1/message.proto queuer/entities/v1/command.protoqueuer/entities/v1/stats.protoqueuer/entities/v1/result.proto"y
PublishConsumerStatsRequest)
consumer_id (	BúBr°R
consumerId/
stats (2.queuer.entities.v1.StatsRstats"R
PublishConsumerStatsResponse2
result (2.queuer.entities.v1.ResultRresult"H
GetSubscribedStreamsRequest)
consumer_id (	BúBr°R
consumerId"T
GetSubscribedStreamsResponse4
streams (2.queuer.entities.v1.StreamRstreamsB„Z/github.com/gsols/goproto/queuer/consumers/v1;v1Ê"GSols\\PHPProto\\Queuer\\Consumers\\v1â+GSols\\PHPProto\\Queuer\\Consumers\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

